// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyApfGQMIBl5rj5Z18tC0BMOB8wz4xMKEWY',
    appId: '1:746736885742:web:68d16a2172f92b69a478ff',
    messagingSenderId: '746736885742',
    projectId: 'social-app-569ce',
    authDomain: 'social-app-569ce.firebaseapp.com',
    storageBucket: 'social-app-569ce.appspot.com',
    measurementId: 'G-BEP2M71T6L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB3uzdmQMI74mVOfSzb6XND-NGmSC3Y4eE',
    appId: '1:746736885742:android:a25cb3780e75646da478ff',
    messagingSenderId: '746736885742',
    projectId: 'social-app-569ce',
    storageBucket: 'social-app-569ce.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDn_L5yaU5rJqMxk23GSC5XQiMdwy4V-xc',
    appId: '1:746736885742:ios:384d5662a5146015a478ff',
    messagingSenderId: '746736885742',
    projectId: 'social-app-569ce',
    storageBucket: 'social-app-569ce.appspot.com',
    androidClientId: '746736885742-lm21610hsv1a4i714mq9mhdvaea39lue.apps.googleusercontent.com',
    iosBundleId: 'com.example.socialApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDn_L5yaU5rJqMxk23GSC5XQiMdwy4V-xc',
    appId: '1:746736885742:ios:7665f0f816c2842ca478ff',
    messagingSenderId: '746736885742',
    projectId: 'social-app-569ce',
    storageBucket: 'social-app-569ce.appspot.com',
    androidClientId: '746736885742-lm21610hsv1a4i714mq9mhdvaea39lue.apps.googleusercontent.com',
    iosBundleId: 'com.example.socialApp.RunnerTests',
  );
}
